{% set name = "biber" %}
{% set version = "2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/Linux/{{ name }}-linux_x86_64.tar.gz # [linux]
  url: https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/OSX_Intel/{{ name }}-darwin_x86_64.tar.gz # [osx]

build:
  number: 0
  script: mkdir -p $PREFIX/bin && mv biber $PREFIX/bin/
  include_recipe: False
  binary_relocation: False


test:
  commands:
    - biber --help

about:
  home: http://github.com/plk/biber
  license: Artistic-2.0
